package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"time"

	"github.com/bzp2010/schedule/internal/database/models"
	"github.com/bzp2010/schedule/internal/handler/graphql/generated"
	models1 "github.com/bzp2010/schedule/internal/handler/graphql/models"
)

// Timeout is the resolver for the timeout field.
func (r *inputTaskConfigurationShellResolver) Timeout(ctx context.Context, obj *models.TaskConfigurationShell, data int64) error {
	obj.Timeout = time.Duration(data) * time.Millisecond
	return nil
}

// Method is the resolver for the method field.
func (r *inputTaskConfigurationWebhookResolver) Method(ctx context.Context, obj *models.TaskConfigurationWebhook, data models1.HTTPMethod) error {
	obj.Method = string(data)
	return nil
}

// InputTaskConfigurationShell returns generated.InputTaskConfigurationShellResolver implementation.
func (r *Resolver) InputTaskConfigurationShell() generated.InputTaskConfigurationShellResolver {
	return &inputTaskConfigurationShellResolver{r}
}

// InputTaskConfigurationWebhook returns generated.InputTaskConfigurationWebhookResolver implementation.
func (r *Resolver) InputTaskConfigurationWebhook() generated.InputTaskConfigurationWebhookResolver {
	return &inputTaskConfigurationWebhookResolver{r}
}

type inputTaskConfigurationShellResolver struct{ *Resolver }
type inputTaskConfigurationWebhookResolver struct{ *Resolver }
